//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recetas
    {
        public Recetas()
        {
            this.Reservas = new HashSet<Reservas>();
            this.Eventos = new HashSet<Eventos>();
        }
    
        public int IdReceta { get; set; }
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public int TiempoCoccion { get; set; }
        public string Descripcion { get; set; }
        public string Ingredientes { get; set; }
        public byte Tipo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<Reservas> Reservas { get; set; }
        public virtual ICollection<Eventos> Eventos { get; set; }

        public virtual string TipoString
        {
            get
            {
                Dictionary<int, string> dic = new Dictionary<int, string>();
                dic.Add(1, "Gourmet");
                dic.Add(2, "Diet");
                dic.Add(3, "Casera");
                dic.Add(4, "Vegetariana");
                return dic[this.Tipo];
            }
            set { this.TipoString = value; }
        }
    }
}
